# Generated by Django 3.0.7 on 2021-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20210204_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootsignal',
            name='type',
            field=models.CharField(default='Linux', max_length=20),
            preserve_default=False,
        ),
    ]
