# Generated by Django 3.1.14 on 2022-09-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20220907_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootsignal',
            name='bootToken',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BootSignals', to='toys.boottoken'),
        ),
    ]
