# Generated by Django 3.1.14 on 2022-09-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_auto_20220907_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootsignal',
            old_name='bootToken',
            new_name='token',
        ),
    ]
